### ISSUE TITLE
Animation Stoped Working with Multiple Input Key

### ISSUE THREAD

**Issue by ARTHUR2WOW** [glitch-escape/glitch-escape#251] opened 2020-03-31 21:03 UTC
The player's animation stopped playing when you press two direction keys at the same time on the keyboard.

**Comment by SeijiEmery** [comment] 2020-04-02 20:06
are those opposite directional keys? if so, working as intended, assuming that player stops moving. Here's the code for player movement from `PlayerControls.cs`:
```C#
        //
        // getters for 2d move + look inputs
        //
        public Vector2 moveInput {
            get {
                var input = Gamepad.current?.leftStick.ReadValue() ?? Vector2.zero;
                if (input.magnitude > 0f) {
                    buttonPollInfo.lastGamepadPressTime = Time.time;
                    ApplyGamepadInputCurve(ref input);
                }
                var kb = Keyboard.current;
                if (kb.aKey.isPressed) { input.x -= 1f; buttonPollInfo.lastKeyboardPressTime = Time.time; }
                if (kb.dKey.isPressed) { input.x += 1f; buttonPollInfo.lastKeyboardPressTime = Time.time; }
                if (kb.sKey.isPressed) { input.y -= 1f; buttonPollInfo.lastKeyboardPressTime = Time.time; }
                if (kb.wKey.isPressed) { input.y += 1f; buttonPollInfo.lastKeyboardPressTime = Time.time; }
                if (input.magnitude > 1f) input.Normalize();
                return input;
            }
        }
```
(ie. opposite keys cancel, and the run animation is triggered to stop when the player is not moving, ie. `moveInput.magnitude < some very small threshold`)

If this is happening for any other simultaneous key presses, or for any animations outside of the player run cycle, then yeah that's a bug :/

**Comment by ARTHUR2WOW** [comment] 2020-04-02 21:12
So I found a situation that would trigger this bug. Quickly press the W key then hold the S key (vice versa works too), then the player can still move in any direction but the animation stopped playing.

Maybe we shouldn't stop the animation when playing is not moving? Instead maybe we could control the animation play speed with the move input magnitude, or use an animator controller.

**Comment by SeijiEmery** [comment] 2020-04-03 22:12
Huh. Yeah, that's how it's supposed to work. Maybe it's using legacy input for one thing and PlayerControls for another, or something (in which case it's fixed on the refactor branch); otherwise this might just be an animation bug that we can fix somehow. Thanks for the heads up!

**Closed** 2020-06-03 22:59 UTC
